### ISSUE TITLE
Version: 3.41.5 is failing with error ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by sushilkar** [atlassian-api/atlassian-python-api#1295] opened 2024-01-16 06:20 UTC
https://pypi.org/project/atlassian-python-api/3.41.5/

```
11:34:03     from atlassian import Jira
11:34:03   File "/opt/vz/1.0/lib/python3.8/site-packages/atlassian/__init__.py", line 5, in <module>
11:34:03     from .confluence import Confluence
11:34:03   File "/opt/vz/1.0/lib/python3.8/site-packages/atlassian/confluence.py", line 10, in <module>
11:34:03     from bs4 import BeautifulSoup
11:34:03 ModuleNotFoundError: No module named 'bs4'
```

**Comment by ragchuck** [comment] 2024-01-16 07:09
Same for me! Our Pipelines failed this morning because of this.

**Comment by Lenormju** [comment] 2024-01-16 08:39
I added `!=3.41.5` to my version constraints.
Using Poetry for my project management :
```toml
[tool.poetry.dependencies]
atlassian-python-api = "^3.39.0, !=3.41.5"  # https://github.com/atlassian-api/atlassian-python-api/issues/1295
```

**Comment by PopoviciMarian** [comment] 2024-01-16 08:45
Same for me!

**Comment by FCamborda** [comment] 2024-01-16 08:56
Our pipelines are also broken.
The usage of bs4 (https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L10) is not properly declared:
https://github.com/atlassian-api/atlassian-python-api/blob/master/setup.py#L28

Please add it and deploy a new release.

Improvement suggestion: Use https://github.com/tweag/FawltyDeps

**Comment by gonchik** [comment] 2024-01-16 09:49
Hello, sorry for that release, I have not known issue with bs4. 
I will release ASAP with that PR https://github.com/atlassian-api/atlassian-python-api/pull/1296

**Comment by gonchik** [comment] 2024-01-16 09:50
@FCamborda  thanks for the  https://github.com/tweag/FawltyDeps

**Comment by moonrail** [comment] 2024-01-16 10:48
Hey @gonchik,

this did not fix it completely.

Installs via PyPi currently lead to incomplete installations, as `setup.py` does not reference `beautifulsoup4` as dependency:
https://github.com/atlassian-api/atlassian-python-api/blob/3.41.5/setup.py#L28

Therefore pip does not install package `beautifulsoup4` and usage of this client leads to:

```python
venv/lib/python3.11/site-packages/atlassian/confluence.py:10: in <module>
    from beautifulsoup4 import BeautifulSoup
ModuleNotFoundError: No module named 'beautifulsoup4'
```

Please add it as a dependency and release a hotfix.

**Comment by marc-woerner-idexx** [comment] 2024-01-16 11:01
I am facing the same issue as @moonrail . Please provide a workaround.

**Comment by schroeni96** [comment] 2024-01-16 11:31
The same issue appears to be in 3.41.6. which one of our build jobs just picked up

**Comment by tichavskym** [comment] 2024-01-16 11:44
The problem isn't just about installing the dependency, but also about importing it, as @gsemet already mentioned in [#1296](https://github.com/atlassian-api/atlassian-python-api/pull/1296#issuecomment-1893510653).

On my installation of Fedora 39 (corporate build), Python 3.12.1, I install BeautifulSoup as `pip install beautifulsoup4`, but I have to import it as `from bs4 import ...`. Which means, I cannot use this package as of right now, because it is doing `from beautifulsoup4 import ...`, see output bellow

```python
(venv) [mtichavs@t14csb middleware-cve-mapping (linking-jiras *)]$ python
Python 3.12.1 (main, Dec  8 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from atlassian import Jira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mtichavs/middleware-cve-mapping/venv/lib/python3.12/site-packages/atlassian/__init__.py", line 5, in <module>
    from .confluence import Confluence
  File "/home/mtichavs/middleware-cve-mapping/venv/lib/python3.12/site-packages/atlassian/confluence.py", line 10, in <module>
    from beautifulsoup4 import BeautifulSoup
ModuleNotFoundError: No module named 'beautifulsoup4'
>>> from beautifulsoup4 import BeautifulSoup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'beautifulsoup4'
>>> from bs4 import BeautifulSoup
>>>
```

**Comment by bagerard** [comment] 2024-01-16 13:16
what's missing now is adding `beautifulsoup4` to the setup.py so it gets pulled automatically during installation

**Comment by moonrail** [comment] 2024-01-16 13:31
I cannot understand how there can be automatic tests and such basic issues go through undetected.
Then why the overhead of testing in the first place? To look good at first glance?
At least the import error should have been detected by automatic testing.

In my opinion at least this should be done to prevent this issue from being repeated:
* Consolidate all package dependencies in a single place (why have a requirements.txt in the first place, if you have a package? And even if you absolutely want to use a requirements.txt, you can simply source this file in setup.py)
* Install the package in automatic testing and let pip install all dependencies automatically - do not install them beforehand or individually (see tox.ini, where beautifulsoup4 is hardcoded)
  * This way automatic tests will fail if dependencies are not correctly declared
  * Also currently tests run e.g. with unconstrained `requests` while requirements.txt pins via `requests>=2.8.1`, which leads to incorrect test results
* Re-check your test pipeline if it correctly runs tests, as obviously a very basic import error was not a blocker for releasing and uploading new versions and packages

**Comment by MultiLi** [comment] 2024-01-16 14:00
![image](https://github.com/atlassian-api/atlassian-python-api/assets/16979290/7995789d-fbb7-4ba9-a453-f052fa3039e8)
That's what happened after updating to 3.41.6

**Comment by zbika73** [comment] 2024-01-16 15:13
About `requirements.txt` file: please check this PR https://github.com/atlassian-api/atlassian-python-api/pull/1298

**Comment by wwakabobik** [comment] 2024-01-16 15:30
Same here, 

![image](https://github.com/atlassian-api/atlassian-python-api/assets/1824047/47b1fbd2-5ea7-4309-8c9b-e139527f7ad9)

**Comment by gonchik** [comment] 2024-01-16 22:17
Hi! I see I am going to upload to do it.

**Comment by vineetpandey** [comment] 2024-01-17 05:23
for me the same error, failing our pipelines due to this:

`>>> from atlassian import Jira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\atlassian\__init__.py", line 5, in <module>
    from .confluence import Confluence
  File "C:\Python\lib\site-packages\atlassian\confluence.py", line 10, in <module>
    from beautifulsoup4 import BeautifulSoup
ModuleNotFoundError: No module named 'beautifulsoup4'`

**Comment by gonchik** [comment] 2024-01-17 07:57
Merged all changes, in 30 min I will release it

**Comment by gonchik** [comment] 2024-01-17 08:10
Hi! 

I am really sorry for that mistake. 
I have uploaded the 3.41.7 version with hotfix version.

I will be happy to see more pull requests.

Cheers,
GT

**Comment by sushilkar** [comment] 2024-01-17 09:58
Thank you @gonchik

**Comment by bagerard** [comment] 2024-01-17 09:58
Thanks for the fix and quick resolution, that's appreciated :+1:  

Note that there is a side effect here (extra dependency) https://github.com/atlassian-api/atlassian-python-api/issues/1301

**Closed** 2024-01-21 22:20 UTC
